export const PERMISSIONS = Object.freeze({
  SIGN_FUNDING_AGREEMENT: '36',
  VIEW_FUNDING_AGREEMENT: '37',
  DOWNLOAD_FUNDING_AGREEMENT: '38',
  UPDATE_SELF: '43',
  ADD_USERS: '44',
  EDIT_USERS: '45',
  DELETE_USERS: '46',
  VIEW_ORG_INFORMATION: '47',
  CHANGE_ORG_INFORMATION: '48',
  VIEW_USERS: '55',
});
