export const PERMISSIONS = Object.freeze({
  UPDATE_SELF: '43',
  ADD_USERS: '44',
  EDIT_USERS: '45',
  DELETE_USERS: '46',
  VIEW_ORG_INFORMATION: '47',
  CHANGE_ORG_INFORMATION: '48',
  VIEW_USERS: '55',
});
