export const PERMISSIONS = Object.freeze({
  // Enrolment Report
  EDIT_DRAFT_ER: '20',
  ADJUST_EXISTING_ER: '21',
  SUBMIT_ENROLMENT_REPORT: '22',
  VIEW_ER: '23',
  // Applications/Renewals
  CREATE_NEW_APPLICATION: '24',
  SUBMIT_NEW_APPLICATION: '25',
  CREATE_RENEWAL_PCF: '26',
  SUBMIT_RENEWAL_PCF: '27',
  VIEW_SUBMITTED_PCF: '28',
  DOWNLOAD_PCF_PDF: '29',
  // View Funding Agreements
  SIGN_FUNDING_AGREEMENT: '36',
  VIEW_FUNDING_AGREEMENT: '37',
  DOWNLOAD_FUNDING_AGREEMENT: '38',
  // Closures
  REQUEST_CLOSURE: '39',
  REMOVE_CLOSURE: '40',
  EDIT_CLOSURE: '41',
  VIEW_CLOSURES: '42',
  // Resources
  UPDATE_SELF: '43',
  ADD_USERS: '44',
  EDIT_USERS: '45',
  DELETE_USERS: '46',
  VIEW_USERS: '55',
  // Account Management
  VIEW_ORG_INFORMATION: '47',
  CHANGE_ORG_INFORMATION: '48',
  CHANGE_PRIMARY_CONTACT: '49',
  VIEW_FACILITY_INFORMATION: '50',
  UPDATE_FACILITY_INFORMATION: '51',
  VIEW_LICENCE_INFORMATION: '52',
  VIEW_PARENT_FEES: '53',
  VIEW_FACILITY_CLOSURES: '54',
});
