//TODO: this really should be a lookup in dynamics
const CHILD_AGE_CATEGORY_TYPES = new Map();
CHILD_AGE_CATEGORY_TYPES.set('0-18', '0 to 18 months');
CHILD_AGE_CATEGORY_TYPES.set('18-36', '18 to 36 months');
CHILD_AGE_CATEGORY_TYPES.set('3Y-K', '3 Years to Kindergarten');
CHILD_AGE_CATEGORY_TYPES.set('OOSC-K', 'Out of School Care - Kindergarten');
CHILD_AGE_CATEGORY_TYPES.set('OOSC-G', 'Out of School Care - Grade 1+');
CHILD_AGE_CATEGORY_TYPES.set('PRE', 'Preschool');

const CHILD_AGE_CATEGORY_ORDER = new Map();
CHILD_AGE_CATEGORY_ORDER.set('0-18', 1);
CHILD_AGE_CATEGORY_ORDER.set('18-36', 2);
CHILD_AGE_CATEGORY_ORDER.set('3Y-K', 3);
CHILD_AGE_CATEGORY_ORDER.set('OOSC-K', 4);
CHILD_AGE_CATEGORY_ORDER.set('OOSC-G', 5);
CHILD_AGE_CATEGORY_ORDER.set('PRE', 6);

//Jen changed these string values ^^ for the lookup mapping to work -- now they match EXACTLY what comes back from the Dynamics API

const ACCOUNT_TYPE = Object.freeze({
  FACILITY: 100000001,
  ORGANIZATION: 100000000,
});

const SCAN_RESULTS = Object.freeze({
  VIRUS_FOUND: 'FOUND',
});
const CCOF_LICENSE_FACILITY_ACCOUNT_STATUSES = Object.freeze({
  DRAFT: 100000001,
});
const CCOF_APPLICATION_TYPES = Object.freeze({
  NEW: 100000000,
  FACILITY: 100000001,
  RENEW: 100000002,
});

const CHANGE_REQUEST_STATUS_CODES = Object.freeze({
  INCOMPLETE: 1,
  SUBMITTED: 3,
  PROCESSING: 4,
  WITH_PROVIDER: 5,
  INELIGIBLE: 6,
  APPROVED: 7,
  CANCELLED: 8,
});

const APPLICATION_STATUS_CODES = Object.freeze({
  NEW: null,
  DRAFT: 1,
  SUBMITTED: 3,
  WITHDRAWN: 4,
  // Additional status codes not from Dynamics
  APPROVED: 10,
  'ACTION REQUIRED': 11,
});

const CHANGE_REQUEST_EXTERNAL_STATUS_CODES = Object.freeze({
  INCOMPLETE: 1,
  SUBMITTED: 2,
  'ACTION REQUIRED': 3,
  INELIGIBLE: 4,
  APPROVED: 5,
  CANCELLED: 6,
});

const CCOF_STATUS_CODES = Object.freeze({
  SUBMITTED: 1,
  'ACTION REQUIRED': 2,
  ACTIVE: 3,
  INACTIVE: 4,
  CANCELLED: 5,
});

const ORGANIZATION_PROVIDER_TYPES = Object.freeze({
  GROUP: 100000000,
  FAMILY: 100000001,
});

const OPTIN_STATUS_CODES = Object.freeze({
  OUT: 0,
  IN: 1,
});

const CCFRI_STATUS_CODES = Object.freeze({
  APPROVED: 3,
  DRAFT: 2,
  SUBMITTED: 1,
  NOT_APPROVED: 4,
  INELIGIBLE: 5,
  'ACTION REQUIRED': 6,
  'Opt-Out': 7,
  NEW: 8,
  'MTFI Requested': 9,
  'MTFI Approved': 10,
  'MTFI Action Required': 13,
});

const ECEWE_STATUS_CODES = Object.freeze({
  SUBMITTED: 1,
  APPROVED: 3,
  DRAFT: 2,
  INELIGIBLE: 4,
  'ACTION REQUIRED': 5,
  'Opt-Out': 6,
  NEW: 7,
});

const PROGRAM_YEAR_STATUS_CODES = Object.freeze({
  CURRENT: 1,
  INACTIVE: 2,
  FUTURE: 3,
  HISTORICAL: 4,
  'FAR FUTURE': 5,
});

const FACILITY_AGE_GROUP_CODES = Object.freeze({
  1: '0 to 18 months',
  2: '18 to 36 months',
  3: '3 Years to Kindergarten',
  4: 'Out of School Care - Kindergarten',
  5: 'Out of School Care - Grade 1+',
  6: 'Preschool',
});

const LICENCE_CATEGORIES = Object.freeze({
  GROUP_CHILD_CARE_UNDER_36_MONTHS: 1,
  GROUP_CHILD_CARE_30_MONTHS_TO_SCHOOL_AGE: 2,
  GROUP_CHILD_CARE_SCHOOL_AGE: 3,
  MULTI_AGE_CHILD_CARE: 4,
  MULTI_AGE_CHILD_CARE_FAMILY: 5,
  IN_HOME_MULTI_AGE_FAMILY: 6,
  FAMILY_CHILD_CARE: 7,
  PRESCHOOL: 8,
  SCHOOL_AGE_CARE_ON_SCHOOL_GROUNDS: 9,
});

const CHANGE_REQUEST_TYPES = Object.freeze({
  LEGAL_ORG_NAME_CHANGE: 100000000,
  ORG_MAILING_ADDRESS: 100000001,
  FACILITY_ADDRESS: 100000002,
  FACILITY_NAME: 100000003,
  LICENSE_CHANGE: 100000004,
  NEW_FACILITY: 100000005,
  SERVICE_DETAIL_CHANGE: 100000006,
  PARENT_FEE_CHANGE: 100000007,
  CLOSURE_UPDATE: 100000008,
  CONTACT_INFORMATION_CHANGE: 100000009,
  BUSINESS_HOURS: 100000010,
  LEGAL_ENTITY_OWNERSHIP: 100000011,
  DATE_DIRECT_DEPOSIT_INFO: 100000012,
  PDF_CHANGE: 100000013,
  NEW_CATEGORY: 100000014,
  NEW_CLOSURE: 100000015,
  EDIT_EXISTING_CLOSURE: 100000016,
  REMOVE_A_CLOSURE: 100000017,
});

const ROLES = Object.freeze({
  ORG_ADMIN: '10',
  FAC_ADMIN_ADVANCED: '11',
  FAC_ADMIN_BASIC: '13',
  READ_ONLY: '12',
});

const PERMISSIONS = Object.freeze({
  // Enrolment Report
  EDIT_DRAFT_ER: '20',
  ADJUST_EXISTING_ER: '21',
  SUBMIT_ENROLMENT_REPORT: '22',
  VIEW_ER: '23',
  // Applications/Renewals
  CREATE_NEW_APPLICATION: '24',
  SUBMIT_NEW_APPLICATION: '25',
  CREATE_RENEWAL_PCF: '26',
  SUBMIT_RENEWAL_PCF: '27',
  VIEW_SUBMITTED_PCF: '28',
  DOWNLOAD_PCF_PDF: '29',
  // Change Requests
  MTFI: '30',
  ORGANIZATION_CHANGE: '31',
  ADD_NEW_FACILITY: '32',
  LICENCE_CHANGE: '33',
  OTHER_CHANGES: '34',
  VIEW_A_CR: '35',
  // View Funding Agreements
  SIGN_FUNDING_AGREEMENT: '36',
  VIEW_FUNDING_AGREEMENT: '37',
  DOWNLOAD_FUNDING_AGREEMENT: '38',
  // Closures
  REQUEST_CLOSURE: '39',
  REMOVE_CLOSURE: '40',
  EDIT_CLOSURE: '41',
  VIEW_CLOSURES: '42',
  // Resources
  UPDATE_SELF: '43',
  ADD_USERS: '44',
  EDIT_USERS: '45',
  DELETE_USERS: '46',
  VIEW_USERS: '55',
  // Account Management
  VIEW_ORG_INFORMATION: '47',
  CHANGE_ORG_INFORMATION: '48',
  CHANGE_PRIMARY_CONTACT: '49',
  VIEW_FACILITY_INFORMATION: '50',
  UPDATE_FACILITY_INFORMATION: '51',
  VIEW_LICENCE_INFORMATION: '52',
  VIEW_PARENT_FEES: '53',
  VIEW_FACILITY_CLOSURES: '54',
  VIEW_PROGRAMS_VACANCIES: '56',
  EDIT_PROGRAMS_VACANCIES: '57',
  VIEW_PAYMENT_INFORMATION: '59',
});

const UUID_VALIDATOR_VERSION = 'loose';

module.exports = {
  ACCOUNT_TYPE,
  APPLICATION_STATUS_CODES,
  CCFRI_STATUS_CODES,
  CCOF_LICENSE_FACILITY_ACCOUNT_STATUSES,
  CCOF_APPLICATION_TYPES,
  CCOF_STATUS_CODES,
  CHANGE_REQUEST_EXTERNAL_STATUS_CODES,
  CHANGE_REQUEST_STATUS_CODES,
  CHANGE_REQUEST_TYPES,
  CHILD_AGE_CATEGORY_ORDER,
  CHILD_AGE_CATEGORY_TYPES,
  ECEWE_STATUS_CODES,
  FACILITY_AGE_GROUP_CODES,
  LICENCE_CATEGORIES,
  OPTIN_STATUS_CODES,
  ORGANIZATION_PROVIDER_TYPES,
  PROGRAM_YEAR_STATUS_CODES,
  PERMISSIONS,
  SCAN_RESULTS,
  ROLES,
  UUID_VALIDATOR_VERSION,
};
