//TODO: this really should be a lookup in dynamics
const CHILD_AGE_CATEGORY_TYPES = new Map();
CHILD_AGE_CATEGORY_TYPES.set('0-18', '0 to 18 months');
CHILD_AGE_CATEGORY_TYPES.set('18-36', '18 to 36 months');
CHILD_AGE_CATEGORY_TYPES.set('3Y-K', '3 Years to Kindergarten');
CHILD_AGE_CATEGORY_TYPES.set('OOSC-K', 'Out of School Care - Kindergarten');
CHILD_AGE_CATEGORY_TYPES.set('OOSC-G', 'Out of School Care - Grade 1+');
CHILD_AGE_CATEGORY_TYPES.set('PRE', 'Preschool');

const CHILD_AGE_CATEGORY_ORDER = new Map();
CHILD_AGE_CATEGORY_ORDER.set('0-18', 1);
CHILD_AGE_CATEGORY_ORDER.set('18-36', 2);
CHILD_AGE_CATEGORY_ORDER.set('3Y-K', 3);
CHILD_AGE_CATEGORY_ORDER.set('OOSC-K', 4);
CHILD_AGE_CATEGORY_ORDER.set('OOSC-G', 5);
CHILD_AGE_CATEGORY_ORDER.set('PRE', 6);

//Jen changed these string values ^^ for the lookup mapping to work -- now they match EXACTLY what comes back from the Dynamics API

const ACCOUNT_TYPE = Object.freeze({
  FACILITY: 100000001,
  ORGANIZATION: 100000000,
});

const CCOF_APPLICATION_TYPES = Object.freeze({
  NEW: 100000000,
  FACILITY: 100000001,
  RENEW: 100000002,
});

const CHANGE_REQUEST_STATUS_CODES = Object.freeze({
  INCOMPLETE: 1,
  SUBMITTED: 3,
  PROCESSING: 4,
  WITH_PROVIDER: 5,
  INELIGIBLE: 6,
  APPROVED: 7,
  CANCELLED: 8,
});

const APPLICATION_STATUS_CODES = Object.freeze({
  NEW: null,
  DRAFT: 1,
  SUBMITTED: 3,
  WITHDRAWN: 4,
  // Additional status codes not from Dynamics
  APPROVED: 10,
  'ACTION REQUIRED': 11,
});

const APPLICATION_TEMPLATE_VERSIONS = [
  { id: 1, isActive: false, note: 'Original application template' },
  { id: 2, isActive: true, note: 'Mar 2025: CCFRI-4450, CCFRI-4568' },
];

const CHANGE_REQUEST_EXTERNAL_STATUS_CODES = Object.freeze({
  INCOMPLETE: 1,
  SUBMITTED: 2,
  'ACTION REQUIRED': 3,
  INELIGIBLE: 4,
  APPROVED: 5,
  CANCELLED: 6,
});

const CCOF_STATUS_CODES = Object.freeze({
  SUBMITTED: 1,
  'ACTION REQUIRED': 2,
  ACTIVE: 3,
  INACTIVE: 4,
  CANCELLED: 5,
});

const ORGANIZATION_PROVIDER_TYPES = Object.freeze({
  GROUP: 100000000,
  FAMILY: 100000001,
});

const OPTIN_STATUS_CODES = Object.freeze({
  OUT: 0,
  IN: 1,
});

const CCFRI_STATUS_CODES = Object.freeze({
  APPROVED: 3,
  DRAFT: 2,
  SUBMITTED: 1,
  NOT_APPROVED: 4,
  INELIGIBLE: 5,
  'ACTION REQUIRED': 6,
  'Opt-Out': 7,
  NEW: 8,
  'MTFI Requested': 9,
  'MTFI Approved': 10,
  'MTFI Action Required': 13,
});

const ECEWE_STATUS_CODES = Object.freeze({
  SUBMITTED: 1,
  APPROVED: 3,
  DRAFT: 2,
  INELIGIBLE: 4,
  'ACTION REQUIRED': 5,
  'Opt-Out': 6,
  NEW: 7,
});

const PROGRAM_YEAR_STATUS_CODES = Object.freeze({
  CURRENT: 1,
  INACTIVE: 2,
  FUTURE: 3,
  HISTORICAL: 4,
  'FAR FUTURE': 5,
});

const FACILITY_AGE_GROUP_CODES = Object.freeze({
  1: '0 to 18 months',
  2: '18 to 36 months',
  3: '3 Years to Kindergarten',
  4: 'Out of School Care - Kindergarten',
  5: 'Out of School Care - Grade 1+',
  6: 'Preschool',
});

const CHANGE_REQUEST_TYPES = Object.freeze({
  LEGAL_ORG_NAME_CHANGE: 100000000,
  ORG_MAILING_ADDRESS: 100000001,
  FACILITY_ADDRESS: 100000002,
  FACILITY_NAME: 100000003,
  LICENSE_CHANGE: 100000004,
  NEW_FACILITY: 100000005,
  SERVICE_DETAIL_CHANGE: 100000006,
  PARENT_FEE_CHANGE: 100000007,
  CLOSURE_UPDATE: 100000008,
  CONTACT_INFORMATION_CHANGE: 100000009,
  BUSINESS_HOURS: 100000010,
  LEGAL_ENTITY_OWNERSHIP: 100000011,
  DATE_DIRECT_DEPOSIT_INFO: 100000012,
  PDF_CHANGE: 100000013,
  NEW_CATEGORY: 100000014,
});

module.exports = {
  CHILD_AGE_CATEGORY_TYPES,
  ACCOUNT_TYPE,
  APPLICATION_STATUS_CODES,
  APPLICATION_TEMPLATE_VERSIONS,
  CCOF_STATUS_CODES,
  CCFRI_STATUS_CODES,
  ECEWE_STATUS_CODES,
  ORGANIZATION_PROVIDER_TYPES,
  FACILITY_AGE_GROUP_CODES,
  OPTIN_STATUS_CODES,
  PROGRAM_YEAR_STATUS_CODES,
  CCOF_APPLICATION_TYPES,
  CHILD_AGE_CATEGORY_ORDER,
  CHANGE_REQUEST_TYPES,
  CHANGE_REQUEST_EXTERNAL_STATUS_CODES,
  CHANGE_REQUEST_STATUS_CODES,
};
