# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI Frontend

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - "feature/**"
      - "Feature/**"
      - "fix/*"
      - "Fix/*"
      - "ccfri-*"
    paths:
      - "frontend/src/**"
  pull_request:
    branches: [main]
    paths:
      - "frontend/src/**"
      - "frontend/src/**"

jobs:
  test:
    name: Run ESLint
    runs-on: ubuntu-24.04

    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.16.x"
      - run: npm ci
      - run: npm run lint
  cypress-run:
    name: Run Component Tests
    runs-on: ubuntu-24.04
    needs: test

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress component tests
        uses: cypress-io/github-action@b8ba51a856ba5f4c15cf39007636d4ab04f23e3c
        with:
          component: true

  # TODO: Uncomment after project is set up in sonar
  # sonarcloud:
  #   name: Build (Sonar Cloud)
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         # Disabling shallow clone is recommended for improving relevancy of reporting
  #         fetch-depth: 0
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: '14.x'
  #     - name: SonarCloud Scan
  #       uses: sonarsource/sonarcloud-github-action@master
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  #with:
  #args: >
  #-Dsonar.exclusions=**/test/**,.github/**/*,*.md
  #-Dsonar.organization=bcgov-sonarcloud
  #-Dsonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
  #-Dsonar.project.monorepo.enabled=true
  #-Dsonar.projectKey=${{ github.event.repository.name }}
  #-Dsonar.sources=frontend
  #-Dsonar.tests=frontend/tests
