name: Cypress Component Tests

on:
  workflow_call:

jobs:
  cypress-component:
    name: Run Component Tests
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cypress component tests
        uses: cypress-io/github-action@v6
        with:
          component: true
          working-directory: frontend
