name: Cypress Component Tests

on:
  workflow_call:

jobs:
  cypress-component:
    name: Run Component Tests
    runs-on: ubuntu-24.04

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress component tests
        env:
          TERM: dumb
        run: |
          npm run test:component:headless
