name: Cypress end-to-end tests
on: 
  workflow_dispatch:
jobs:
  cypress-run:
    name: Run Cypress E2E tests
    runs-on: ubuntu-24.04
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with: 
          working-directory: ./test/cypress-e2e
          browser: electron
          wait-on: ${{ secrets.CYPRESS_PORTAL_BASE_URL }}
          spec: ./cypress/e2e/1-portal-login/portal-login-happy-path-e2e.cy.js
        env:
          CYPRESS_PORTAL_USERNAME: ${{ secrets.CYPRESS_PORTAL_USERNAME }}
          CYPRESS_PORTAL_PASSWORD: ${{ secrets.CYPRESS_PORTAL_PASSWORD }}
          CYPRESS_PORTAL_BASE_URL: ${{ secrets.CYPRESS_PORTAL_BASE_URL }}

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-screenshots
          path: test/cypress-e2e/cypress/screenshots