name: Cypress Component Tests

on:
  workflow_call:

jobs:
  cypress-component:
    name: Run Component Tests
    runs-on: ubuntu-24.04

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress component tests
        run: |
          npm run test:component:headless
