name: 2 QA - Deploy Frontend

env:
  # EDIT your repository secrets to log into your OpenShift cluster and set up the context.
  # See https://github.com/redhat-actions/oc-login#readme for how to retrieve these values.
  # To get a permanent token, refer to https://github.com/redhat-actions/oc-login/wiki/Using-a-Service-Account-for-GitHub-Actions
  OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
  OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
  # EDIT to set the kube context's namespace after login. Leave blank to use your user's default namespace.
  OPENSHIFT_NAMESPACE: ${{ secrets.CCOF_NAMESPACE_NO_ENV }}-dev

  # SPLUNK_TOKEN: ${{ secrets.SPLUNK_TOKEN }}

  # EDIT to change the image registry settings.
  # Registries such as GHCR, Quay.io, and Docker Hub are supported.
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  IMAGE_REGISTRY_USER: ${{ github.actor }}
  IMAGE_REGISTRY_PASSWORD: ${{ github.token }}

  DOCKER_ARTIFACTORY_REPO: artifacts.developer.gov.bc.ca/docker-remote
  ARTIFACTORY_REPO: artifacts.developer.gov.bc.ca

  APP_NAME: 'ccof'
  REPO_NAME: "educ-ccof"
  #grabs the branch name from github dynamically
  BRANCH: ${{ github.ref_name }}
  IMAGE_NAME: "frontend"
  APP_ENVIRONMENT: "qa"

  NAMESPACE: ${{ secrets.CCOF_NAMESPACE_NO_ENV }}

  MIN_REPLICAS: "1"
  MAX_REPLICAS: "2"
  MIN_CPU: "50m"
  MAX_CPU: "100m"
  MIN_MEM: "200Mi"
  MAX_MEM: "250Mi"
  # SITE_URL should have no scheme or port. It will be prepended with https://
  HOST_ROUTE: ${{ secrets.SITE_URL }}
  CA_CERT: ${{ secrets.CA_CERT }}
  CERTIFICATE: ${{ secrets.CERTIFICATE }}
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The image tag to deploy'
        required: true
        type: string

jobs:
  openshift-ci-cd:
    name: Deploy Frontend to QA
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-24.04
    environment: qa

    outputs:
      ROUTE: ${{ steps.deploy-and-expose.outputs.route }}
      SELECTOR: ${{ steps.deploy-and-expose.outputs.selector }}

    steps:
    - name: Print Workflow Dispatch Inputs and Env Vars
      uses: shayki5/print-workflow-dispatch-inputs@d33d9a2262e8c0b8c726540184b654402705a87f #v1.0.1
      with:
        add_to_summary: 'true'
        print_env_vars: 'false'

    - name: Check for required secrets
      uses: actions/github-script@10b53a9ec6c222bb4ce97aa6bd2b5f739696b536 #v4.2.0
      with:
        script: |
          const secrets = {
            OPENSHIFT_SERVER: `${{ secrets.OPENSHIFT_SERVER }}`,
            OPENSHIFT_TOKEN: `${{ secrets.OPENSHIFT_TOKEN }}`,
          };

          const GHCR = "ghcr.io";
          if (`${{ env.IMAGE_REGISTRY }}`.startsWith(GHCR)) {
            core.info(`Image registry is ${GHCR} - no registry password required`);
          }
          else {
            core.info("A registry password is required");
            secrets["IMAGE_REGISTRY_PASSWORD"] = `${{ secrets.IMAGE_REGISTRY_PASSWORD }}`;
          }

          const missingSecrets = Object.entries(secrets).filter(([ name, value ]) => {
            if (value.length === 0) {
              core.error(`Secret "${name}" is not set`);
              return true;
            }
            core.info(`Secret "${name}" is set`);
            return false;
          });

          if (missingSecrets.length > 0) {
            core.setFailed(`At least one required secret is not set in the repository. \n` +
              "You can add it using:\n" +
              "GitHub UI: https://docs.github.com/en/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-a-repository \n" +
              "GitHub CLI: https://cli.github.com/manual/gh_secret_set \n" +
              "Also, refer to https://github.com/redhat-actions/oc-login#getting-started-with-the-action-or-see-example");
          }
          else {
            core.info(`All the required secrets are set`);
          }

    - name: Check out repository
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5a #v4.3.1
      with:
        ref: ${{ env.BRANCH }}
        persist-credentials: false

    - name: Install oc
      uses: redhat-actions/openshift-tools-installer@144527c7d98999f2652264c048c7a9bd103f8a82 #v1.13.1
      with:
        oc: 4.16

    - name: Deploy
      env:
        TAG: ${{ inputs.tag }}
        BANNER_COLOR: ${{ vars.BANNER_COLOR }}
        BANNER_ENVIRONMENT: ${{ vars.BANNER_ENVIRONMENT }}
        VUE_APP_BCEID_REG_URL: ${{ secrets.VUE_APP_BCEID_REG_URL }}
      run: |
        set -eux
        # Login to OpenShift and select project
        oc login --token="$OPENSHIFT_TOKEN" --server="$OPENSHIFT_SERVER"
        oc project "$OPENSHIFT_NAMESPACE"
        # Cancel any rollouts in progress
        oc rollout cancel "deployment/$APP_NAME-$IMAGE_NAME-$APP_ENVIRONMENT" 2> /dev/null \
            || true && echo "No rollout in progress"

        # Process and apply deployment template
        oc process \
          -f tools/openshift/frontend.deployment.yaml \
          -p APP_NAME="$APP_NAME" \
          -p REPO_NAME="$REPO_NAME" \
          -p BRANCH="$BRANCH" \
          -p NAMESPACE="$OPENSHIFT_NAMESPACE" \
          -p TAG="$TAG" \
          -p MIN_REPLICAS="$MIN_REPLICAS" \
          -p MAX_REPLICAS="$MAX_REPLICAS" \
          -p MIN_CPU="$MIN_CPU" \
          -p MAX_CPU="$MAX_CPU" \
          -p MIN_MEM="$MIN_MEM" \
          -p MAX_MEM="$MAX_MEM" \
          -p HOST_ROUTE="$HOST_ROUTE" \
          -p CA_CERT="$CA_CERT" \
          -p CERTIFICATE="$CERTIFICATE" \
          -p PRIVATE_KEY="$PRIVATE_KEY" \
          -p APP_ENVIRONMENT="$APP_ENVIRONMENT" \
          -p BANNER_COLOR="$BANNER_COLOR" \
          -p BANNER_ENVIRONMENT="$BANNER_ENVIRONMENT" \
          -p VUE_APP_BCEID_REG_URL="$VUE_APP_BCEID_REG_URL" \
          | oc apply -f -

        # Start rollout (if necessary) and follow it
        oc rollout restart "deployment/$APP_NAME-$IMAGE_NAME-$APP_ENVIRONMENT" 2> /dev/null \
            || true && echo "Rollout in progress"

        # Get status, returns 0 if rollout is successful
        oc rollout status "deployment/$APP_NAME-$IMAGE_NAME-$APP_ENVIRONMENT"

